### ISSUE TITLE
Maximum width

### ISSUE THREAD

**Issue by rafeblandford** [davatron5000/FitVids.js#10]
It would be helpful to add support for maximum width (i.e. specify a max width beyond which video should not be fluid, this helps prevent videos from getting too big).

I have tried to do this myself, but without success. I'm sure there's a way to do this, but not being a JavaScript Ninja could not work out where to make the changes.

For other looking at this - a work around which does work is, of course, to place the iframe is `<p> / <div>` and add a max-width css statement to that. However that requires extra markup, which seems a shame for a drop in solution.

**Comment by nevergone** [comment]
This is merged and committed?
