### ISSUE TITLE
Vimeo autoplay duplicates audio in IE11

### ISSUE THREAD

**Issue by Tankzor** [davatron5000/FitVids.js#149]
Weird(?) one here...

If a vimeo video is set to autoplay, and the iframe has allowfullscreen="true", fitVids will cause the audio of the video to be duplicated.

Looks to be from jQuery.wrap() on line 68.

The whole video may be duplicated but just detached from the DOM? Not sure.
Only an issue in IE11.

Simple example: http://www.tests.massivedev.com/vimeo/

I've taken to wrapping iframes manually, and have removed the wrap() call (and the check for the existing container on line 60).

**Comment by davekiss** [comment]
Running into this issue on my end, can either of you describe the "wrap manually" process? I'm retrieving my videos onclick via the Vimeo oembed api and don't have the html available on pageload.

**Comment by davatron5000** [comment]
http://alistapart.com/article/creating-intrinsic-ratios-for-video

Here's the article FitVids is based on. You basically need to some HTML:

```
<div class="video-wrapper">
  <iframe></iframe>
</div>
```

And some CSS

```
.video-wrapper {
  position: relative;
  height: 0;
  padding-bottom: 56.25%; /* 16:9 Aspect Ratio */
}

.video-wrapper iframe {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
```

FitVids just automates the aspect ratio for you.
