### ISSUE TITLE
Setting proposal: padding-top

### ISSUE THREAD

**Issue by leoj3n** [davatron5000/FitVids.js#150]
### Thesis

Based on my findings in [this comment](https://github.com/davatron5000/FitVids.js/issues/130#issuecomment-31316365), specification of `padding-top` percentages per `fitVid()` instance should be allowed.
#### Discussion

1) Should this be implemented as an additional setting?
2) Or should this be done externally as a forceful override using either CSS or JS?

**Comment by chapeladmin** [comment]
This is not the same as #152 unless the rounding errors can be greater than 10s of pixels. From #152 it seems more like off by a pixel in the case of odd division by 2 rounding issues. I can confirm setting padding-top to 56% eliminates all the issues for vimeo. To get around this, I just have a vimeo-specific wrapper and use css and !important to override the element style.
