### ISSUE TITLE
Issue with youtube api

### ISSUE THREAD

**Issue by andersthorborg** [davatron5000/FitVids.js#170]
Thanks for a great tool. I use it for all of my projects.

Recently I had to embed youtube videos using the YouTube Iframe API (as well as the Player API), to be able to subscribe to player events.

This resulted in some unexpeted/unstable behavior, and i originally thought it was an instability in the actual youtube api (https://code.google.com/p/gdata-issues/issues/detail?id=5788) since it was not consistent. 

Trying to fix the issue I started over, an thereby disabled the FitVids functionality. I realized, that as soon I used fitVids i got the unexpected behavior and everything worked fine without. I have no idea what causes it and why, so this is just a heads up to others that might be struggling with the same issue.

Best,

Anders

**Comment by eliaspn** [comment]
I had the same problem, I followed this article http://avexdesigns.com/responsive-youtube-embed/ and it worked. I used percentage for padding-top to get rid of black edges
