### ISSUE TITLE
YouTube videos repeated after hitting browser's 'back' button

### ISSUE THREAD

**Issue by dabernathy89** [davatron5000/FitVids.js#203]
Steps to recreate problem:
- call Fitvids on multiple YouTube videos on a page
- follow a standard link on the page
- hit your browser's back button
- all videos with Fitvids called on them will be replaced by one of the videos
- the issue will also effect some videos that have not had Fitvids called on them

I have only tested this with YouTube videos, and only with Chrome 40.0.2214.111 on OS X 10.10.2 (Yosemite).

JsFiddle and Codepen don't support external links, so here is an example of the issue. I've included very minimal CSS and jQuery.

https://www.danielabernathy.com/fitvids-bug/

**Comment by dabernathy89** [comment]
Yeah I should have searched through the issues history before posting this.

**Comment by dabernathy89** [comment]
Although I will say the issue does *not* appear without FitVids being called - it appears when this has been brought up previously it occurs regardless of FitVids' inclusion.

**Comment by davatron5000** [comment]
Yeah. It seems to be an iFrame memory management issue in Chrome, also noted in: #191, #190, #33. There's not much we can do... I'll reach out to people at Chrome/Google and try and see where they're at on this.

File as: **Can't fix**

**Comment by richgcook** [comment]
Any thoughts/news on this @dabernathy89 @davatron5000
