### ISSUE TITLE
Only resize videos on mobile devices?

### ISSUE THREAD

**Issue by includecreative** [davatron5000/FitVids.js#208]
Hi there,

Is there anyway within the script to only use FitVids if the viewport is less than a specified width? We need to resize video's for mobile devices, but on the larger desktop view of the site, they become a little too big.

Any idea if this is doable?

Thanks

**Comment by davatron5000** [comment]
Not currently. There are a couple issues that have asked for and addressed that (#10, #19). You could wrap your videos in another max width wrapper like this:

```
// Run FitVids
$('#myTarget').fitVids();
// Find all the wrappers and then wrap them in a max width DIV
$('.fluid-width-video-wrapper').wrap('<div class="fluid-width-video-wrapper-max-width">');
```

Then in your css:

```
.fluid-width-video-wrapper-max-width { max-width: 600px; }
```

It'll probably be a feature in FitVids 2.0 which has a rough beta here:
http://codepen.io/davatron5000/pen/9fef11884a883855d8a1a187bac0cbfe
