### ISSUE TITLE
Multiple Vimeo videos getting swapped randomly

### ISSUE THREAD

**Issue by ndimatteo** [davatron5000/FitVids.js#210]
I'm having a weird issue where in certain instances when I have multiple videos on a page, fitvids seems to be putting 1 of the videos in place of all the rest of the videos, instead of doing each separately.

You can test this out here: https://twentyoverten.com (scroll down a bit to see the two videos).

1. The videos should load properly on initial load
2. Now simply click a link (try the explore providence button) on that page
3. Go back via the back button
4. Video 1 will be playing in both spots

I have no idea why this would be happening, I even tried wrapping the fitvids() in an .each() function for the videos, but it still occurs.

Any ideas here?

**Comment by davatron5000** [comment]
This is the Chrome Back Button bug https://code.google.com/p/chromium/issues/detail?can=2&q=iframe&colspec=ID%20Pri%20M%20Iteration%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&id=395533&thanks=395533&ts=1405933036

Unfortunately we can't fix it. It's based on how the browser is managing it's iframe memory state.

**Comment by davatron5000** [comment]
Fixed in #231
