### ISSUE TITLE
Bump version to v1.1.1

### ISSUE THREAD

**Issue by sn3p** [davatron5000/FitVids.js#217]
So fitvids-rails wrapper will be updated ;)

**Comment by davatron5000** [comment]
Which version where? In bower?

**Comment by pagegwood** [comment]
Hey @davatron5000 I second the motion for a new tag... Right now the latest pulled from Bower does not have the ignore selector. Btw, ShopTalk rocks.

**Comment by kavykun** [comment]
Can we get an update to bower? I want to use the ignore selector.

**Comment by davatron5000** [comment]
Adding in the `ignore` selector would mean it's a new feature, so `1.2.0` would be more appropriate. Does that sound right to everyone?

**Comment by davatron5000** [comment]
Hey! We did it! It only took a little over a year. 🎉 :facepalm:

```
λ bower install jquery.fitvids
bower jquery.fitvids#*          cached https://github.com/davatron5000/FitVids.js.git#1.2.0
bower jquery.fitvids#*        validate 1.2.0 against https://github.com/davatron5000/FitVids.js.git#*
bower jquery#>= 1.7.0           cached https://github.com/jquery/jquery-dist.git#3.1.1
bower jquery#>= 1.7.0         validate 3.1.1 against https://github.com/jquery/jquery-dist.git#>= 1.7.0
bower fitvids#^1.2.0           install fitvids#1.2.0
bower jquery#>= 1.7.0          install jquery#3.1.1
```
