### ISSUE TITLE
Flexbox and FitVids

### ISSUE THREAD

**Issue by LinusFlax** [davatron5000/FitVids.js#224]
Not sure if this is an issue or just my lack of skills…

I’m using Flexbox to center content, and it seems FitVids isn’t working because of Flexbox. See this fiddle: http://jsfiddle.net/LLjL9b6z/1/

Once you delete the Flexbox CSS it works just fine. But in my project I depend on Flexbox and on Fitvids…

Any ideas to get this to work?

**Comment by davatron5000** [comment]
Looks like your `div.video-container` loses its `width` inside the flexbox. Without a `width` on the parent container, FitVids just calculates it as zero.

```
.video-container {
    width: 100%;
}
```

Adding that appears to fix this. See... http://jsfiddle.net/LLjL9b6z/1/

**Comment by LinusFlax** [comment]
Thanks! You’re right, this fixes the fiddle.
So my problem was somewhere else and I already fixed it in my project.
It had nothing to do with flexbox or FitVids.
