### ISSUE TITLE
Add Facebook support?

### ISSUE THREAD

**Issue by SachaG** [davatron5000/FitVids.js#225]
I feel like Facebook videos are pretty common these days, maybe it could be one of the default supported players?

**Comment by davatron5000** [comment]
@SachaG This is probably a good idea. Do you know any hosted/embedded statistics for FB videos? It seems like there's A LOT of videos, but (anecdotally) are only rarely embedded outside the FB ecosystem.

**Comment by SachaG** [comment]
I'm not sure, but I'm seeing them more and more embedded on Reddit and would like to support them in [Telescope](http://telescopeapp.org), too.

**Comment by SachaG** [comment]
I can probably submit a PR if you think it makes sense to add it.

**Comment by davatron5000** [comment]
Merging with #232
