### ISSUE TITLE
How use fitvid in sahifa theme for responsive video?

### ISSUE THREAD

**Issue by isogfx** [davatron5000/FitVids.js#226]
hi,
how use fitvid?
i use 'sahifa' theme in wordpress,
plz help me for add fitvids code to this theme,

when i use Pulgin fitvids and active checkmark "Add jQuery 1.7.2 from Goodle CDN"
the top Menu of site is not Properly show,

and without active checkmark FitVids Plugin noting work,
plz help me,

thanks
by.

**Comment by davatron5000** [comment]
We'd need more information to see if this a problem with the plugin: Web inspector console errors, etc.

If you're trying to use jQuery with WordPress, I recommend reading this: http://fixingthesejquery.com/#slide1

☝️ This deals with lots of common problems with jQuery.

This doesn't appear to be a problem with plugin, more a question of how to implement. We don't offer support on Github, this is for bugs, I recommend asking this question over on [StackOverflow](http://stackoverflow.com).
