### ISSUE TITLE
FitVids.js not working with Ditty News Ticker WordPress plugin

### ISSUE THREAD

**Issue by dl-110** [davatron5000/FitVids.js#227]
Hey!

I am using fitvidy.js for my website and now I wanted to use the WordPress plugin called Ditty News Ticker (https://en-ca.wordpress.org/plugins/ditty-news-ticker/). But as soon as I use the plugin I receive the following error:

Uncaught TypeError: $(...).fitVids is not a function

Any suggestions how I can get both to work?
Thanks!

**Comment by davatron5000** [comment]
Wordpress is a little weird last I remember. You can't use the `$` sign. You have to use the longhand `jQuery` instead. It'll look something like this.

```
jQuery('#myelement').fitVids()
```

Otherwise... it seems you're maybe not including FItVids in your site. There's a wonderful FitVids WordPress plugin that used to be maintained.

**Comment by dl-110** [comment]
Worked like a charm! Thanks!

**Comment by AlexandraCasser** [comment]
Solved my issue.  Thanks!
