### ISSUE TITLE
Showcase or feature

### ISSUE THREAD

**Issue by llahnoraa** [davatron5000/FitVids.js#228]
Hello.

I love this plugin. I think this is the best one yet. I wanted to let you know that I incorporated for [sfcollege.edu](http://sfcollege.edu) and among other college's microsites such as [sfcollege.edu/1](http://sfcollege.edu/1) and [sfcollege.edu/gators/](http://sfcollege.edu/gators/)

Figured you might want to have this as a showcase on your site? Thank you.

**Comment by davatron5000** [comment]
Thanks @llahnoraa for the submission. We don't have a gallery so-to-speak, but it's great to hear that it's working out for you. Thanks for letting us know.
