### ISSUE TITLE
The right format?

### ISSUE THREAD

**Issue by onigetoc** [davatron5000/FitVids.js#239]
I tryed the css method only with the part 
padding-bottom: 56.25%;

And it look more at the perfect ratio than with Fitvids

What i mean is for exemple, Youtube video still get black band at top and footer
This only css method work perfectly But i still need FitVids for dynamic content but with the perfect ratio.

```
embed-responsive-iframe {
    position: relative;
    padding-bottom: 56.25%;
    /* padding-top: 35px; */
    height: 0;
    overflow: hidden;
}
embed-responsive-iframe iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```

**Comment by smdksu** [comment]
Same issue here

**Comment by davatron5000** [comment]
Do you have any example code, a Reduced Test Case, that you can provide. Something like a CodePen?

Can't really debug what you're doing.  

- Your `embed-responsive-iframe` isn't a valid CSS
- Looks like you're not even using FitVids, you have a hardcoded 16:9 aspect ratio (`padding-bottom: 56.25%`)

FitVids works for videos of all sized based off of their specified height and width. It could be 2:3 aspect, 4:3 aspect, 16:9 aspect, 21:9 aspect... If you want all videos to have 16:9 like your code, you could wrap iFrames with some jQuery:

```
$('iframe').wrap('.embed-responsive-iframe');
```

**Comment by smdksu** [comment]
You can see the issue here: http://ksiteonline.com/why-k-state and here: https://kansaslivingmagazine.com/articles/2016/11/01/the-franklins

When you play the videos black bars show up at the top and bottom.

**Comment by davatron5000** [comment]
I need a reduced test case. "See on my site" is too difficult to debug.

**Comment by smdksu** [comment]
Here ya go: http://codepen.io/smdksu/pen/Obmdmo

**Comment by smdksu** [comment]
Figured it out. Height matters here. If anyone else runs into this issue, mess the height value of the iframe.

**Comment by davatron5000** [comment]
```
<iframe class="media-youtube-player" 
        width="640" height="390" 
        title="A Slice of Manhattan"
        src="//www.youtube.com/embed/p_ldq9teicE?wmode=opaque"
        frameborder="0" allowfullscreen>Video of A Slice of Manhattan</iframe>
```

The height of the video was `390px`, so doing the Intrinsic Ratio math.... `390/640 = .609375 * 100 = 60.9375%` which is what FitVids was calculating.
