### ISSUE TITLE
Flexbox Order & FitVids

### ISSUE THREAD

**Issue by jezthomp** [davatron5000/FitVids.js#241]
Is this a known issue that when flex box ordering is applied it collapses the container of the FitVid and other content slides behind as its doesn’t have a height?

**Comment by davatron5000** [comment]
@jezthomp Do you have a reduced test case?

**Comment by jezthomp** [comment]
No sorry, its local.
Essentially a 2 column grid once on mobile it collapses down but re-ordered with flex box.
The fitvids container if within column 2 its purpose is just for the video, not for the column width.
Once i re-order on mobile the column 2 loses its height and collapses i assume because of the padding added to the video container via FitVids

**Comment by jezthomp** [comment]
Ignore, my css was wrong.

**Comment by davatron5000** [comment]
@jezthomp Glad you got it figured out! Thanks again.
