### ISSUE TITLE
Dynamic content

### ISSUE THREAD

**Issue by Orionds** [davatron5000/FitVids.js#253]
I'm getting data from my database via ajax and appending said data, which contains youtube iframes to the DOM. Iframes loaded when the page first loads respond to fitvids but dynamically loaded content does not. Could anyone please guide me. I apply fitvids to my `body` element like so:` $("body").fitVids();`

**Comment by davatron5000** [comment]
@Orionds You probably need to call `$(body).fitVids();` again after you inject content. FitVids runs once on `$(document).ready()` and then won't run again unless you call it.

Hope that helps. Can't really help further unless we have an editable reduced test case.

**Comment by adam-jones-net** [comment]
I have the same issue, did you get a fix @Orionds  ?

**Comment by adam-jones-net** [comment]
I get Uncaught ReferenceError: body is not defined trying this fix @davatron5000    Any ideas ?

**Comment by davatron5000** [comment]
Ahhh... try this...

```
$(document).ready( function() {
  $('body').fitVids();
});
```

You probably need the `'` quotes around `body` so that jQuery can select the HTML `<body>` element.

**Comment by adam-jones-net** [comment]
Ah of course, thanks so much!
