### ISSUE TITLE
Doesn't work with Twitter video embeds

### ISSUE THREAD

**Issue by mehlkelm** [davatron5000/FitVids.js#257]
FitVids doesn't seem to work with Twitter Video Embeds. See for example https://ia.net/topics/news-from-facebook/

I tried with 
`articleElement.fitVids({ customSelector: "div.twitter-video"});`
to no avail.

Regards, Stefan

**Comment by mehlkelm** [comment]
Hm… seems to work with
`articleElement.fitVids({ customSelector: ".twitter-video"}); `

**Comment by mehlkelm** [comment]
Twitter video embeds should probably work out of the box, but maybe this issue could be closed.

**Comment by davatron5000** [comment]
per the `contributing.md` doc, is there an editable reduced test case demonstrating the issue?

**Comment by mehlkelm** [comment]
No, I couldn't make it work
