### ISSUE TITLE
Implementing fitVids() with vanilla javascript

### ISSUE THREAD

**Issue by isaumya** [davatron5000/FitVids.js#260]
Hi,
while implementing fitVids() I've noticed a weird thing, i.e. if I call `fitVids()` using pure js methods, then it says `fitVids()` is not a function, whereas both jQuery and fitVids.js files have been inserted within the page, but when I do the same thing using jQuery, it works smoothly, I don't understand why. Can anyone explain?

Here is the code example:

### This will give error: 
```
if( document.querySelector(".edu-vid") !== null ) {
	document.querySelector(".edu-vid").fitVids();
}
```

### But this will work fine:
```
if( document.querySelector(".edu-vid") !== null ) {
	jQuery(".edu-vid").fitVids();
}
```
Can anyone explain why? Thanks in advance.

**Comment by davatron5000** [comment]
This version of FitVids is a jQuery plugin so it extends the `jQuery` object. You can see FitVids extending the `jQuery.fn` namespace at the top of the plugin file. https://github.com/davatron5000/FitVids.js/blob/master/jquery.fitvids.js#L15 

So while `document.querySelector( selector )` and `jQuery( selector )` look the same, they're very different.

If you `document.querySelector( selector )` for something, you're returned a native `Element`.  
If you `jQuery( selector )` for something, you're returned a jQuery Object. 

Getting a jQuery Object back means you access to all the jQuery functions like `show()` and `hide()` as well as `fitVids()`. Hope that helps explain it.

Really recommend these slides about "Fixing These jQuery" when you run into jQuery issues. http://fixingthesejquery.com/#slide1

**Comment by isaumya** [comment]
@davatron5000 Thanks a lot for the explanation. Is there any FitVids version which can run using vanilla JS and without using jQuery?

**Comment by davatron5000** [comment]
Yeah. There's quite a few! I would recommend [fluidvids](https://github.com/toddmotto/fluidvids) by @toddmotto 

And then I use [this gist](https://gist.github.com/davatron5000/e9ef20f1d2ba4d9099711064c644d155) but do not support it whatsoever. So use at your own risk.

**Comment by isaumya** [comment]
@davatron5000 Thanks. But if you can consider making a pure js version of fitvids. :)
