### ISSUE TITLE
Using customSelector for other not supported out of the box vendors removes scalling for default

### ISSUE THREAD

**Issue by levsoroka** [davatron5000/FitVids.js#267]
This is really just a question.

If when you choose to target video players from other non supported vendors lets say like this 
```$(".video-item").fitVids({ customSelector: "iframe[src^='https://player.waywire.com'], iframe[src^='https://livestream.com']" });```

this will not then scale supported providers such as youtube or other default.

So it is okay to add them in the customSelector like this?

```$(".video-item").fitVids({ customSelector: "iframe[src^='http://video.columbia.edu'], iframe[src^='https://player.waywire.com'], iframe[src^='https://livestream.com'], iframe[src^='https://vimeo.com/'], iframe[src^='https://www.youtube.com/']" });```

or should there be two different fitVids() calls.

**Comment by davatron5000** [comment]
It should add your custom selectors into the provided video selectors (vimeo, youtube, etc), so you should only need your additions. But there's no real harm in duplicating [as far as I know].

https://github.com/davatron5000/FitVids.js/blob/master/jquery.fitvids.js#L44-L46
