### ISSUE TITLE
iFrame Embed Swapping/Duplicating

### ISSUE THREAD

**Issue by jonathanmoore** [davatron5000/FitVids.js#33]
Recently we started noticing an issue with FitVids where it will cause all the iFrame embeds on the page to swap out for one of the random embeds duplicating the video across the page.  In testing we can reproduce this 100% of the time in the latest versions of Chrome (16.0.912.77) and Safari (5.1.2).  Oddly Firefox 6 & 8 do not have the issue, but Firefox 3.6 behaves the same way.

jsFiddle - http://jsfiddle.net/nAXXY/5/
_Five embeds (Vimeo and Youtube), simple CSS, jQuery 1.7.1 and latest FitVids.js_

**Steps to reproduce:**
1. Load up http://jsfiddle.net/nAXXY/5/
2. Click on any link taking you to a new page or type in a new URL
3. Hit back on your browser
4. Refreshing the page will correct the issue

Video demo - http://cloud.jonathanmoore.com/Ddsv

**Comment by forestkelley** [comment]
Has a solution arisen?  I'm having the same issue with Chrome 41.0.2272.104 (64-bit).
